#%RAML 1.0 Trait
queryParameters:
      destination:
        type: string
        description: query parameter to get the flight info based on destination
        required: true
        example: "SFO"